// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTVHdtF9B_XabBl8MTXTeA9q-5SWLs4Hc',
    appId: '1:892593383500:web:9e890032a2cb3134f32ce9',
    messagingSenderId: '892593383500',
    projectId: 'push-37d1d',
    authDomain: 'push-37d1d.firebaseapp.com',
    storageBucket: 'push-37d1d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHbnAWqF_kO-qWe9wtoTMZQ7xc2gXk6_A',
    appId: '1:892593383500:android:345ec8e6da625cccf32ce9',
    messagingSenderId: '892593383500',
    projectId: 'push-37d1d',
    storageBucket: 'push-37d1d.appspot.com',

  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0gzyLgd5BRJDlWAa4HXxfpsPFf8YirXI',
    appId: '1:892593383500:ios:0f63e271fcefe922f32ce9',
    messagingSenderId: '892593383500',
    projectId: 'push-37d1d',
    storageBucket: 'push-37d1d.appspot.com',
    iosClientId: '892593383500-gd3qfglo2da2r6evencoosbmgf7cutu7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterMaps',
  );
}
